services:
  cache-proxy:
    build: .
    env_file:
      - .env
    ports:
      - 8000:8000
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis

  redis:
    image: redis
    ports:
      - 6379:6379
    environment:
      - REDIS_MAXMEMORY=2gb
      - REDIS_MAXMEMORY_POLICY=allkeys-lru